### ISSUE TITLE
Add LICENCE to repo

### ISSUE THREAD

**Issue by AaronFeledy** [jazzdelightsme/PowershellStub#1]
Thanks for this. I stumbled on it in the winget repo while trying to solve this exact problem. Could you [include an open-source license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository) in this repo so that other projects can use it?

**Comment by jazzdelightsme** [comment]
It's < 100 lines, so I would think it should fall under "de minimis", but sure; added a `LICENSE` just to make it explicit.
